### PR TITLE
Feature: ResourceFarm Recoder

### PR DESCRIPTION
**Pull request by darkautism**
Feature: Add a little panel for resource farm recoder
UI:
image

### CODE REVIEW

**Comment by eai04191** [comment]
Hello! Thank you for submitting your PR.
The idea for this feature is great. It will help many users including me.

Looking at the code and UI, it looks like there are a few things that need to be fixed.
Do you want to do this yourself? If so, I'll do a review and point out what needs to be fixed.
Or would you prefer that I fix it directly?
This is your PR, so you can choose either way. Either way, I will help you merge it.

**Comment by eai04191** [comment]
Also, the main branch is used for releases, so you can't send a PR here. Need to re-send to develop branch

**Comment by darkautism** [comment]
Hi eai04191,

I create a new PR to develop. And change code format.
I do not know what you want about look and feel so this UI is simply. You can change it if you want.

**Comment by eai04191** [comment]
I got it. I make some fix commits to the newer PR and then merge. The fix may take some time.
Thank you for your contribution!

**Pull request closed without merging**
